ExamAspNet/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI.WebControls;
using ExamAspNet.Models;
using static System.Net.Mime.MediaTypeNames;

namespace ExamAspNet.Controllers
{
    public class AdminController : Controller
    {
        private GymContext db = new GymContext();
        public ActionResult Index(int AdminId = 0, string mes = null)
        {
            if (AdminId == 0)
            {
                Session["id"] = null;
                Session["name"] = null;
                return RedirectToAction("LogIn");
            }
            Session["id"] = AdminId.ToString();
            Session["name"] = db.Admins.Find(AdminId).Name;

            return RedirectToAction("Details", new { id = AdminId, msg = mes });
        }

        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(string Password)
        {
            Admin admin = db.Admins.Where(x => x.Password == Password).FirstOrDefault();
            if (admin == null)
            {
                ViewBag.Msg = $"admin is not found. Check your information.";
                return View();
            }
            return RedirectToAction("Index", new { AdminId = admin.Id });
        }

        public ActionResult Details(int? id, string msg = null)
        {
            if (id == null || Session["id"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            string l = Session["id"].ToString();
            if (admin == null || Session["id"].ToString() != id.ToString() || Session["name"].ToString() != admin.Name)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            ViewBag.Msg = msg;
            return View(db.Applications.Where(x=> x.isAccepted == null));
        }

        public ActionResult Accept(int? id)
        {
            if (id == null )
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Application application = db.Applications.Find(id);

            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        [HttpPost, ActionName("Accept")]
        [ValidateAntiForgeryToken]
        public ActionResult AcceptConfirmed(int id)
        {
            Models.Application application = db.Applications.Find(id);
            application.isAccepted = true;
            db.Entry(application).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            int adId = int.Parse(Session["id"].ToString());
            if (AddPractice(application.UserId, application.PracticeId))
            {
                Message message = new Message() { SenderId = 100, UserId = application.UserId, Text = $"Your application to join {application.PracticeName} was accepted" };
                db.Messages.Add(message);
                db.SaveChanges();
                
                return RedirectToAction("Index", new { AdminId = adId });
            }
            return RedirectToAction("Index", new {AdminId = adId,mes = "Error"});
        }

        public ActionResult Reject(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        [HttpPost, ActionName("Reject")]
        [ValidateAntiForgeryToken]
        public ActionResult RejectConfirmed(int id)
        {
            Models.Application application = db.Applications.Find(id);
            application.isAccepted = false;
            db.Entry(application).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();

            Message message = new Message() { SenderId = 100, UserId = application.UserId, Text = $"Your application to join {application.PracticeName} was rejected" };
            db.Messages.Add(message);
            db.SaveChanges();
            int adId = int.Parse(Session["id"].ToString());
            return RedirectToAction("Index", new { AdminId = adId});
        }

        public ActionResult AdminPartial()
        {
            return PartialView();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public bool AddPractice(int userId, int practiceId)
        {
            try
            {
                User user = db.Users.Find(userId);
                Practice practice = db.Practices.Find(practiceId);
                user.Practices.Add(practice);
                db.Entry(practice).State = EntityState.Modified;
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return true;
            }
            catch
            {
                return false;
            }
        }
    }
}

ExamAspNet/Controllers/CoachController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI.WebControls;
using ExamAspNet.Models;

namespace ExamAspNet.Controllers
{
    public class CoachController : Controller
    {
        private GymContext db = new GymContext();

        // GET: Coaches
        public ActionResult Index(int CoachId = 0)
        {
            if (CoachId == 0)
            {
                Session["id"] = null;
                Session["name"] = null;
                return RedirectToAction("LogIn");
            }
            Session["id"] = CoachId.ToString();
            Session["name"] = db.Coaches.Find(CoachId).Name;
            
            return RedirectToAction("Details", new {id = CoachId});
        }

        // GET: Coaches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null || Session["id"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Coach coach = db.Coaches.Find(id);
            if (coach == null || Session["id"].ToString() != id.ToString() || Session["name"].ToString() != coach.Name)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            var temp = coach.Practices.ToList();
            List<Practice> practices = new List<Practice>();
            foreach (var t in temp)
            {
                practices.Add(db.Practices.Where(x => x.Id == t.Id).Include(x => x.Users).Include(x => x.FitProgram).First());
            }
            ViewBag.Practices = practices.OrderBy(x=> x.FitProgram.Title);
            if (coach == null)
            {
                return HttpNotFound();
            }
            return View(practices.OrderBy(x => x.FitProgram.Title));
        }

        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(string Password)
        {
            Coach coach = db.Coaches.Where(x => x.Password == Password).FirstOrDefault();
            if (coach == null)
            {
                ViewBag.Msg = $"Coach is not found. Check your information.";
                return View();
            }
            return RedirectToAction("Index", new { CoachId = coach.Id });
        }


        public ActionResult Message(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.User = db.Users.Find(id);
            ViewBag.CoachId = Int32.Parse(Session["id"].ToString());
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Message([Bind(Include = "SenderId,UserId,Text")] Message message)
        {
            if (ModelState.IsValid)
            {
                message.SenderId = Int32.Parse(Session["id"].ToString());
                db.Messages.Add(message);
                db.SaveChanges();
                return RedirectToAction("Index", new { CoachId = message.SenderId});
            }

            return View(message);
        }

        public ActionResult History(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            ViewBag.User = user;
            ViewBag.Coach = Session["name"].ToString();
            int coachid = Int32.Parse(Session["id"].ToString());
            return PartialView(db.Messages.Where(x=> x.UserId == user.Id && x.SenderId == coachid));
        }
        public ActionResult CoachPartial()
        {
            return PartialView();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExamAspNet/Controllers/GymController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.EnterpriseServices;
using System.Linq;
using System.Net;
using System.Security.Principal;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using ExamAspNet.Models;
using Microsoft.Ajax.Utilities;

namespace ExamAspNet.Controllers
{
    public class GymController : Controller
    {
        private GymContext db = new GymContext();
        public List<string> Pics1 = new List<string>() {"https://images.squarespace-cdn.com/content/v1/555d1abee4b018e272bccf5c/1617802561456-169AYKO0MVJ8QSTXJXUL/Page-One-Pilates-Chicago-West-Loop-Photographer-Melody-Joy-Co-75.jpg?format=750w", "https://images.squarespace-cdn.com/content/v1/555d1abee4b018e272bccf5c/1617805691258-HXVW762RPNQAK21UFYX5/Page-One-Pilates-Chicago-West-Loop-Photographer-Melody-Joy-Co-125.jpg?format=750w", "https://i.pinimg.com/564x/a6/41/5c/a6415cff53d0049c549efee281cbb43c.jpg", "https://i.pinimg.com/236x/94/9c/6b/949c6b2a5681c30b2e557a6bdd88c34f.jpg", "https://i.pinimg.com/564x/3e/63/db/3e63db1ac7e79454f931ac6132a4208b.jpg", "https://i.pinimg.com/564x/d4/e6/25/d4e625b4aba2368967ba0d5374b3bdce.jpg" };
        public List<string> Pics = new List<string>() { "https://media.gettyimages.com/id/1326071979/photo/brunette-girl-doing-pilates-exercise-for-the-oblique-abdominals.jpg?s=2048x2048&w=gi&k=20&c=XfFJb7YmNY1zkpTk3fziRSzZ8C-FKlAd6OSF4UUZdkQ=", "https://media.gettyimages.com/id/1189331298/photo/be-mindful-of-how-awesome-you-are.jpg?s=2048x2048&w=gi&k=20&c=wezWoo1o1xfvL6zKTyW2QNkVfdOkyJz4QiPIIZKRemw=", "https://media.gettyimages.com/id/1433136266/photo/people-doing-cross-training-in-an-health-club.jpg?s=2048x2048&w=gi&k=20&c=Ko2Lfc6pE-HA8n4CSpnnrr-osMkSMtG37n6W0fq6Rrw=", "https://media.gettyimages.com/id/1397575319/photo/stretching-out-in-fitness-class.jpg?s=2048x2048&w=gi&k=20&c=RouEKYgLTxn2wM29aCDfgxMuZQa3HUrJ7PS5jJm39CI=", "https://media.gettyimages.com/id/641794674/photo/fitness-people-working-out-with-battle-ropes.jpg?s=2048x2048&w=gi&k=20&c=gp-7n9v39PrllWeRIIaNS9JZ1iTHcM0hWUFzIBD0GTk=", "https://media.gettyimages.com/id/1287929278/photo/not-your-average-classroom.jpg?s=2048x2048&w=gi&k=20&c=HALqISdVdcuf8vxadrQ1D2_OlLJbUPaauyXmSFNX7Vk=" };
        public ActionResult FitProgramIndex(string msg = "")
        {
            ViewBag.Msg = msg;
            return View(db.FitPrograms.ToList());
        }

        public ActionResult CoachIndex()
        {
            return View(db.Coaches.ToList());
        }

        public ActionResult View1()
        {
            return View();
        }

        public ActionResult Index(int UserId = 0)
        {
            if(UserId == 0)
            {
                Session["id"] = null;
                Session["name"] = null;
                return View();
            }
            Session["id"] = UserId.ToString();
            Session["name"] = db.Users.Find(UserId).Name;
            return View();
        }

        public ActionResult CoachDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Coach coach = db.Coaches.Find(id);
            if (coach == null)
            {
                return HttpNotFound();
            }
            var idF = coach.Practices.Select(x => x.FitProgramId);
            List<FitProgram> list = new List<FitProgram>();
            foreach(var i in idF)
            {
                list.Add(db.FitPrograms.Where(x => x.Id == i).First());
            }
            ViewBag.FitPrograms = list;
            return PartialView(coach);
        }

        public ActionResult FitProgramDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FitProgram fitProgram = db.FitPrograms.Find(id);
            if (fitProgram == null)
            {
                return HttpNotFound();
            }
            ViewBag.Picture = Pics[(int)id - 1];

            var idC = fitProgram.Practices.Select(x => x.CoachId);
            List<Coach> list = new List<Coach>();
            foreach (var i in idC)
            {
                list.Add(db.Coaches.Where(x => x.Id == i).First());
            }
            ViewBag.Coaches = list;

            var idF = fitProgram.Practices.Select(x => x.DayOfWeeks).ToList();
            List<Day>days= new List<Day>();
            foreach (var day in idF)
                foreach (var elem in day)
                    days.Add(elem);

            ViewBag.Days = days.OrderBy(x=> x.DayOfWeek);
            return View(fitProgram);
        }

        public ActionResult FitProgramJoin(int? id)
        {
            if (Session["id"] == null)
                return RedirectToAction("Index", "User", new {msg = "Before joining, You need to Log In or Sign up"});
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FitProgram fitProgram = db.FitPrograms.Find(id);
            if (fitProgram == null)
            {
                return HttpNotFound();
            }
            else
            {
                int UserId = int.Parse(Session["id"].ToString());
                User user = db.Users.Find(UserId);
                ViewBag.User = user;
                ViewBag.Practices = db.Practices.Where(x => x.FitProgramId == fitProgram.Id).Include(x => x.Coach).ToList();
                return View(fitProgram);
            }  
        }

        [HttpPost]
        public ActionResult FitProgramJoin(FitProgram fitProgram, int UserId, int[] selectedPractices)
        {
            FitProgram newFit = db.FitPrograms.Find(fitProgram.Id);
            User user = db.Users.Find(UserId);
            if (Session["id"] == null)
                Session["id"] = UserId.ToString();

            if(selectedPractices == null)
            {
                ViewBag.User = user;
                ViewBag.Practices = db.Practices.Where(x => x.FitProgramId == fitProgram.Id).Include(x => x.Coach).ToList();
                ViewBag.Message = "Choose Practice";
                return View(fitProgram);
            }
            if (user.ClassesNum > user.Practices.Count)
            {
                foreach(var prId in selectedPractices)
                {
                    Practice practice = db.Practices.Find(prId);
                    if(user.Practices.Contains(practice))
                        return RedirectToAction("FitProgramIndex", new { msg = "You've already joined that FitProgram" });
                }


                foreach (var prId in selectedPractices)
                {
                    Practice practice = db.Practices.Find(prId);

                    Application application = new Application() { UserId = user.Id, PracticeId = prId, PracticeName = practice.FitProgram.Title, UserName = user.Name };
                    db.Applications.Add(application);
                    db.SaveChanges();
                }
                
                //foreach (var prId in selectedPractices)
                //{
                //    Practice practice = db.Practices.Find(prId);
                //    user.Practices.Add(practice);
                //    db.Entry(practice).State = EntityState.Modified;
                //}
                //db.Entry(user).State = EntityState.Modified;

                //db.SaveChanges();
                return RedirectToAction("FitProgramIndex");
            }
                return RedirectToAction("FitProgramIndex", new { msg = "You've reached the full record on your Card" });
            
        }

        public ActionResult UserPartial()
        {
            return PartialView();
        }

        public ActionResult Schedule()
        {
            ViewBag.Days = db.Days.OrderBy(x=> x.DayOfWeek).ToList();

            return View(db.Practices.Include(x=> x.Coach).Include(x=> x.FitProgram).OrderBy(x=>x.StartTime).ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExamAspNet/Views/Shared/AdminPartial.cshtml
@if (Session["id"] == null)
{
    <li>@Html.ActionLink("Log In", "LogIn", "Admin")</li>
}
else
{
    <li>@Html.ActionLink($"Hello {Session["name"]}", $"Details/{Session["id"]}", "Admin")</li>
    <li>@Html.ActionLink("Exit", "Index", "Gym")</li>
}

ExamAspNet/Views/Shared/CoachPartial.cshtml
@if (Session["id"] == null)
{
    <li>@Html.ActionLink("Log In", "LogIn", "Coach")</li>
}
else
{
    <li>@Html.ActionLink($"Hello {Session["name"]}", $"Details/{Session["id"]}", "Coach")</li>
    <li>@Html.ActionLink("Exit", "Index", "Gym")</li>
}

ExamAspNet/Views/Shared/UserPartial.cshtml
@if (Session["id"] == null)
{
    <li>@Html.ActionLink("Log In", "LogIn", "User")</li>
    <li>@Html.ActionLink("Sign Up", "SignUp", "User")</li>
}
else
{
<li>@Html.ActionLink($"Hello {Session["name"]}", $"Details/{Session["id"]}", "User")</li>
<li>@Html.ActionLink("Exit", "Index", "Gym")</li>
}

ExamAspNet/Views/Shared/_AdminLayout.cshtml
@using ExamAspNet.Helpers

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="Дополнительные параметры">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @Html.ActionLink("IGNITE", "Index", "Gym", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @Html.Partial("AdminPartial")
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div id="modDialog" class="modal fade">
            <div id="dialogContent" class="modal-dialog"></div>
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/scripts/jquery-1.10.2.js")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
    @RenderSection("scripts", required: false)
</body>
</html>

ExamAspNet/Views/Shared/_Layout.cshtml
@using ExamAspNet.Helpers

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="Дополнительные параметры">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @Html.ActionLink("IGNITE", "Index", "Gym", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Our Coaches", "CoachIndex", "Gym")</li>
                    <li>@Html.ActionLink("Our Activities", "FitProgramIndex", "Gym")</li>
                    <li>@Html.ActionLink("Our Schedule", "Schedule", "Gym")</li>
                    @Html.Partial("UserPartial")
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div id="modDialog" class="modal fade">
            <div id="dialogContent" class="modal-dialog"></div>
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/scripts/jquery-1.10.2.js")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
    @RenderSection("scripts", required: false)
</body>
</html>

ExamAspNet/Views/Shared/_StuffLayout.cshtml
@using ExamAspNet.Helpers

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="Дополнительные параметры">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @Html.ActionLink("IGNITE", "Index", "Gym", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @Html.Partial("CoachPartial")
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div id="modDialog" class="modal fade">
            <div id="dialogContent" class="modal-dialog"></div>
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/scripts/jquery-1.10.2.js")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
    @RenderSection("scripts", required: false)
</body>
</html>